population_size = 20
num_of_layers = 4
elite_size = int(population_size * 0.25)
mutation_rate = 0.5
mutation_factor = 0.2
neurons_lst = [16, 8, 4, 1]
num_of_generations = 400
name_of_file = "nn0.txt"
train_ratio = 0.9
